[package]
name = "wasmtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime-rust = "0.27.0"
# failure = "0.1.8"
anyhow = "1.0.57"

